### ISSUE TITLE
Moving part of a rule to a new rule

### ISSUE THREAD

**Issue by MrHug** [pimotte/nomic#19]
Is it possible within the current rules to move part of an existing mutable rule to a new mutable rule within a single PR?

Personally I do not think so as this would require the modification of a rule and the introduction whereas rule 103 uses "or" a lot,but perhaps I am misreading something.

**Comment by pimotte** [comment]
You'd be able to introduce a new rule which contains the part you want to move, and after adoption, propose another rule-change which modifies the original rule?

**Comment by MrHug** [comment]
Hmm yeah... I think I'll work on a proposal later that will allow a literal movement of part of a rule to ~~another~~ _new_ rule.

**Comment by MrHug** [comment]
Closed with #312
