### ISSUE TITLE
The people vs @MrHug 1

### ISSUE THREAD

**Issue by pimotte** [pimotte/nomic#34]
I accuse @MrHug of having violated rule 309 in his submission of pull-request #32.

This makes @MrHug the defendant of this trial, and me the prosecutor. I will split my actions in this role to a separate comment.

**Comment by pimotte** [comment]
The prosecution calls forth @arthurbik for jury duty.

The prosecution will wait with an opening statement until the defendant has called forth someone for jury duty.

**Comment by MrHug** [comment]
The defendant sees no need to call forth an additional jury member, thus the jury for this trial will consist of only @arthurbik.

After the prosecution has given its opening statement, I will respond in kind.

**Comment by pimotte** [comment]
As prescribed by rule 309, the title of a pull request must include the number of the rule-change it encompasses, if such a number is assigned. 

As can be seen in the changelog of the pull request at #32, the title did not include the assigned number at the time of submission. Since there was a moment in time where this was not the case, the prosecution asserts that @MrHug has violated rule 309. 

While a reduction of 0 points would be in order if 324 were to be adopted, at this point in time, it is not. Since the prosecution feels a guilty verdict is in order, a reduction of 1 point is demanded.

**Comment by MrHug** [comment]
I fully acknowledge the fact that my PR did not at all times include the assigned number (323) in the title. However, to use the terminology of the currently under consideration rule 324, I will plead Not Guilty and thus request the jury does not reduce the number of points I currently have.
My defense is twofold:
1. I hold that rule 309 does not explicitly state the number needs to be included at the time of the creation of the PR. It simply states it needs to be included in the title, not when this needs to be included.
2. I also hold that the game has not been disrupted by this oversight in any way. As the title change happened before any discussion had taken place, no problems were created by it. In fact I would argue it happened before any discussion could have taken place. As GitHub timestamps show, the edit was made in the same minute as the creation of the PR. The defense argues that all possible actions were taken immediately to resolve this oversight as quickly as possible and that no damage has been done to the state of the game, the flow of the game, or even the enjoyment of the game.

Ultimately I can say only this, whereas I believe the prosecution is right in putting me on Trial for this oversight, I do not feel a Guilty verdict is in order and will stick to my pleading of "Not Guilty" as a result.

Guilty verdicts, in my opinion, should be reserved for breaking of the rules that:
- require someone to fix the gamestate
- disrupt the flow of the game
- harm the enjoyment/spirit of the game as experienced by players.

**Comment by jdonkervliet** [comment]
This is crazy. :astonished:

**Comment by MrHug** [comment]
The defense requests the public that is unaffiliated to the Trial to please refrain from commenting unless they have evidence or testimony relevant to the proceedings.

**Comment by jdonkervliet** [comment]
On what grounds?

**Comment by MrHug** [comment]
None, hence it being phrased as a _request_ :wink:

**Comment by jdonkervliet** [comment]
:fu:

**Comment by pimotte** [comment]
In response to point 1: The timing of the addition is irrelevant. By virtue of the existence of this pull request without the number in the title, a rule violation has occurred.

The prosecution agrees with the assertion the defendant makes in point 2. However, the non-disruption of the game is not a reason for a non-guilty verdict.
The prosecution states that guilty verdicts should reflect whether a rule was violated, nothing more, nothing less. Now, but especially in a world where rule-change 324 were to be adopted. The magnitude of the punishment should be influenced by, among others, the points the defendant names. This is why a minimal punishment has been demanded.

**Comment by MrHug** [comment]
Hmm, actually the defense would like to involve @jdonkervliet in this trial and demand an explanation of the prosecution as to why @jdonkervliet has not been put on trial for his violation of rule 309 in his PR found here #12.

As the timestamps indicate rule 309 was passed on the twelfth of May at 3:41 PM. However PR #12 as only changed to include a number in its title on the fourteenth of May at 7:20 PM. This means that for over 48 hours PR #12 did not meet the criteria outlined in rule 309, (a period that is over 2800 times larger than that of the defendant).

Regarding point 1: I would be happy to answer any questions the jury might have on this point, but I feel that the prosecution and I will not be reaching agreement on how this rule should be read. I still maintain it does not specify when the number should be included, which I argue could be read as "it should be included at some point".

Regarding point 2: This will possibly change under rule 324 (PR #33), but I still maintain that the notion of Guilty should be reserved for disruptive behavior. A "gedoogbeleid" would be perfectly fine in situations where an accidental mistake was made.

**Comment by pimotte** [comment]
As a prosecutor, I would like to state there is no obligation for a prosecutor to pursue all violations in parallel, even if they were violations. In particular it would be efficient to allow precedence to occur before going into another trial.

**Comment by pimotte** [comment]
As a player, I would like to state that @jdonkervliet s violation was before the enactment of rule 311. By rule 108, there is no way to prosecute a player for a fact that has occurred before the enactment of this rule.

**Comment by jdonkervliet** [comment]
:relieved:

**Comment by MrHug** [comment]
I would say that should also be the answer of the prosecution :wink:
After all I would go for an offense that is 2800x times larger (literally in this case) before going a small one as this precedence would be far stronger.

The fact that no prosecution was possible at the time however does not mean that @jdonkervliet could not have been attended to this violation of the rule. So clearly the prosecution thought it was fine to ignore the violation at the time, then why not also forgive and forget the oversight that was immediately fixed by the defendant?

EDIT: In fact the prosecution had no issues with reporting other violations by invoking judgement as shown by #24, even when they were his own. I am not saying that punishments would have followed for the violation, but if the prosecutions really cares about violations such as the one for which I am on Trial, I wonder why he did not use this earlier violation to make his opinions clear.

**Comment by pimotte** [comment]
Since that particular situation was triggered by an action not initiated by @jdonkervliet, it would be in the spirit of the rules to allow reasonable time (which is now informally being defined as 72 hours) before reminding him to include the number. In particular, if he had shown any other activity working on that PR while not adding the number to the title, I would have reminded him.

In this case, the violation was clearly initiated by the defendant.

**Comment by MrHug** [comment]
But it was fixed before any actions that could potentially have influenced the enjoyment or even flow of the game could have taken place, within a fraction of the timespan referred to as reasonable by the prosecution. Furthermore no other activity on the PR had taken place before the number was added in the title in this case as well. Thus all conditions that the prosecution lists as to why there was no need to reprimand @jdonkervliet hold, except for the "clearly initiated by the defendant" claim.

This I can not deny, I was the one who clicked on "create PR", however I still maintain that no damage was done, just like in @jdonkervliet's case, and that as a result a Guilty verdict would not be appropriate in this scenario. I repeat my earlier claim that:

> Guilty verdicts, in my opinion, should be reserved for breaking of the rules that:
> - require someone to fix the gamestate
> - disrupt the flow of the game
> - harm the enjoyment/spirit of the game as experienced by players.

Unless either the prosecution or jury has any more questions to ask or arguments to present during this trial, the defense rests and would like to only _request_ that a closing argument may be presented after the jury has decided that it has no questions to ask.

**Comment by pimotte** [comment]
The prosecution suggests to proceed as the defendant suggests, in that after the jury has asked all questions they deem prudent, the prosecution, followed by the defendant, will have the opportunity to present a closing statement before the jury goes into deliberation. 

The prosecution rests until closing statements.

**Comment by arthurbik** [comment]
Things have happened...

One could say that "submitting a pull request" constitutes the creation of a PR, reading it over to see how it turned out and changing anything that was not intended. I would like to ask the prosecution to argue against this definition of  "submitting a pull request".

 I would also like to ask if prosecution believes that the defendant had the intention to break a rule.

**Comment by pimotte** [comment]
One could say that, and if that were in the rules, the prosecution would agree that that would be a perfectly acceptable definition. However, given that it is not defined in the rules, the prosecution would say it follows that the definition is that which is the most common interpretation, which would be the submission of a pull request. If the prosecution would name the actions you describe, it might call that "submitting and adjusting  a pull request".

The prosecution does not believe the defendant had the intention to break a rule. However, this should only affect the measure of punishment, not the kind of verdict. In particular, rule 311 specifically mentions unwittingly violating a rule.

**Comment by arthurbik** [comment]
The jury has no more questions. So lets go the closing statements.

**Comment by pimotte** [comment]
The prosecution believes all relevant factors have been considered. The prosecution rests.

**Comment by MrHug** [comment]
I too believe I have made my point clear, however I also would like to ask the jury to consider how easy a mistake this is to make and how easy it would be for any other player to end up in my position. If we set a precedent of finding people Guilty for simple mistakes that lead to no disruption of gameplay, enjoyment, or any other aspect of the game then we will spend more time conducting Trials during which we demand no punishment then coming up with new rules. Don't get me wrong, I like going head to head with someone just as much as the next guy, but I do wonder if that is the path we want to take. 

So member of the jury I ask you, please, to  consider not only the fact that this trial was born out of a mistake that was resolved in less than one minute, but also consider the precedent that you are now setting for the future of all minor mistakes, Trials, and this game.

With that, the defense rests.

**Comment by arthurbik** [comment]
For the sake of the enjoyment of the game, I declare that, in the context of the rule currently numbered as 309, "submitting a pull request" constitutes the creation of a PR, reading it over to see how it turned out and changing anything that was not intended. So a player has an amount of time to correct mistakes.

I am not going so say how long "an amount of time" is or should be, but it is at least two minute. So the Jury finds the Defendant NOT GUILTY.

**Comment by MrHug** [comment]
![](http://66.media.tumblr.com/752d4cf0a7bb0a6b409d31e6ddd6be6f/tumblr_my6tk0Pi7n1rw0ey4o1_500.gif)
