### ISSUE TITLE
Proceedings in the game during a Trial

### ISSUE THREAD

**Issue by MrHug** [pimotte/nomic#35]
I believe it is currently not specified whether or not changes to the gamestate are allowed during an ongoing Trial. This is the case for Judgement (the gamestate is frozen).

As this means it is possible for the gamestate to change during a Trial, this could be disastrous, right?

**Comment by pimotte** [comment]
I'd say this is a problem only once at the point of the change, there is disagreement about rules, in which case, Judgement would be invoked to resolve it. I see it as a good thing to fix this in the rules, but I don't see there being any problems in the near future. (Even if this is going in the direction that I think it is :P)

**Comment by MrHug** [comment]
Hmmm ok, so at least we agree that it is not forbidden.

I think I would like a rule (amendment) to at least make this explicit, but for now we will simply deal with rule changes during a trial as they come in I guess :wink:

**Comment by MrHug** [comment]
Ok so I think that means #29 can be safely merged then? I will refrain from doing so as I am already on trial for a violation, but I believe it can be merged eventhough a Trial is in progress.

**Comment by pimotte** [comment]
Since there is no visible disagreement at this point, I'm going to go ahead and merge #29. If someone does disagree, then they can invoke judgement. (Not start a trial, unless they feel I am "directly contradicting a rule".)
