### ISSUE TITLE
What is lying?

### ISSUE THREAD

**Issue by jdonkervliet** [pimotte/nomic#36]
Since we are now in the process of a trial (#34), I was wondering about the following phrase in rule 311:

> Lying during a Trial is an offensive for which a player can be put on Trial.

If a Jury decides the defendant is Guilty, but the defendant pleaded Not-Guilty, perhaps backed up by some arguments, is the defendant lying?

To make it more concrete:
1. What is our definition of a lie?
2. Can a player lie without knowing it?
3. If not, how do other players know if the player in question was aware of his/her lie or not?

**Comment by MrHug** [comment]
Are you invoking judgement? If so, please name the judge.

**Comment by jdonkervliet** [comment]
The Judge is decided by the rule, right? I don't think I need to appoint anybody. Otherwise I will name myself the Judge.

**Comment by jdonkervliet** [comment]
I guess @arthurbik is Judge here.

**Comment by MrHug** [comment]
Correct, but you should tell us who should be the judge based on the rule.

**Comment by jdonkervliet** [comment]
I don't think so.

**Comment by MrHug** [comment]
Hmmk maybe not, but for clarity (like in #24) I think it would be best ;)

**Comment by arthurbik** [comment]
If a Jury decides the defendant is Guilty, but the defendant pleaded Not-Guilty, perhaps backed up by some arguments, is the defendant lying?

I see pleading Not-Guilty the same as saying "I do not want the Jury to find me Guilty.", so it would not be a lie solely because the Jury did find someone Guilty.

What is our definition of a lie?

A Lie is a statement, uttered by an entity, which is not correct. 

Can a player lie without knowing it?

I think so, yes. This is in line with the fact that a player can break a rule without the intention to do so. Of course, whether a player had the intent to lie should be considered by the Jury if a Trial about the (possible) lie would occur.

**Comment by arthurbik** [comment]
Do anyone wish to go against this Judgement?

**Comment by pimotte** [comment]
I do not wish to overturn this Judgement. I would say we can wait a little bit if @jdonkervliet wants to ask for further specifications, but otherwise, this would be final.

**Comment by MrHug** [comment]
I can live with this, so I will not object this ruling. As such no unanimity to overturn this decision can be reached.

**Comment by MrHug** [comment]
Oh @pimotte beat me to it, well let's wait for @jdonkervliet then ;)

**Comment by jdonkervliet** [comment]
How is this intent to be evaluated? In most cases it would be impossible to prove.

Even though the Jury might _consider_ the intent, in principle making a statement that you think is true, but turns out to be false is currently punishable.

**Comment by MrHug** [comment]
(Gallery, not judge comment:) Yes, but only on trial though. So just don't claim things on Trial that can be verified to be lies (i.e. times of commits etc)

**Comment by arthurbik** [comment]
A Jury can decide and consider what the Jury wants to, as long as the members of the Jury follow the rules. 

So basically, a Jury can mess with the Defendant, which is of course always true.

**Comment by jdonkervliet** [comment]
@MrHug that seems like a tall order. How would you all feel about a rule-change that removes lying as a punishable offense for the defendant?

**Comment by MrHug** [comment]
I would be against that. It is called Perjury and to me that is an offense. 

I agree with @arthurbik the jury can do whatever they like, but that's why I already included that they should keep the punishment between the bounds of prosecution and defense. I would consider other restrictions on the power of the jury, but to me lying will have to remain an offense.

**Comment by jdonkervliet** [comment]
@MrHug depends if the defendant is under oath, right?

**Comment by MrHug** [comment]
In real life? Yes.
In this game I left that out, but for the metaphor you may assume the defendant to be under oath at all times EDIT: during the trial.

**Comment by arthurbik** [comment]
The Defendant (the same as any player) must follow the rules at all times, which currently state no lying.

**Comment by jdonkervliet** [comment]
I think that is not true @MrHug. In the Netherlands the defendant is not under oath. Only witnesses and experts.

**Comment by MrHug** [comment]
Hmm fair enough, well in our game they are, at least under the current rules.

A rule-change can of course change that, though I will be voting against ;)

**Comment by jdonkervliet** [comment]
Which leads to this weird situation, where you say you are not guilty, then being found guilty, which implies that you made an incorrect statement, which is a lie, so you have committed an offense again.

**Comment by arthurbik** [comment]
Saying that you are not Guilty and pleading Not-Guilty are two different things.

**Comment by MrHug** [comment]
Agree with @arthurbik, but @jdonkervliet also has a point. Perhaps a rule stating what we define to be a lie wouldn't hurt, I would like something about "facts" or "evidence" in there.

**Comment by jdonkervliet** [comment]
I think we can close this issue. I have made clear my opinion on the current state of this rule.

**Comment by MrHug** [comment]
Fair enough and I will be looking forward to your rule-change proposal. :wink:
