### ISSUE TITLE
Which player?

### ISSUE THREAD

**Issue by jdonkervliet** [pimotte/nomic#37]
If a Judgement process regards the interpretation of a rule, who is "a player" in the following context:

> When Judgment has been invoked, a player may not begin a turn without the consent of a majority of the other players. 
- Rule 305

**Comment by MrHug** [comment]
Again are you invoking judgement? If so, please name the judge.

I think I can answer this however by saying: all players

**Comment by jdonkervliet** [comment]
And here. @arthurbik

**Comment by MrHug** [comment]
Hmm not sure if @arthurbik would be judge here, as someone is already judge in #36 now...?

**Comment by jdonkervliet** [comment]
> If at least one player disagrees about the legality of a move or the interpretation or application of a rule, a Judge is to decide the question. If no player is currently a Judge, then the player, among the players not currently having an open issue labelled "Judgement", with the Github handle alphanumerically previous to the player, who started an open issue labelled "Judgement" first amongst all players currently having an open issue labelled "Judgement", is to be the Judge. If all players have an open issue labelled "Judgement", then a Judge is decided by a majority vote.

If @arthurbik is Judge in the other matter, he is currently a Judge, so no Judge needs to be selected.

**Comment by jdonkervliet** [comment]
Also, if 'a player' means all players, than each player should get a majority vote from _all other_ players before he/she is allowed to start a new turn.

Also, I would like to include in this Judgement, what happens if one of the players does _not_ receive a majority vote to be allowed to start new turns. No rule exists that states if and how this vote should be repeated. Is this player than put on non-active forever? I guess one way around this, is the non-active player again invoking Judgement to issue a new voting round.

**Comment by MrHug** [comment]
Well after judgement he should at least be free to start turns again? (I am not the judge, just taking part in the discussion :P)

**Comment by pimotte** [comment]
Peanut gallery agreeing with @MrHug here.

**Comment by jdonkervliet** [comment]
That is not stated anywhere, so let's see what the Judge says.

**Comment by arthurbik** [comment]
The intent behind "a player" is any player. So that line applies to all players. 

The "When" in

> When Judgment has been invoked, a player may not begin a turn without the consent of a majority of the other players. 

should be read as "As long as", so all players are free to start a turn when Judgement is over.

The rule does not explicitly states that a player must obtain the consent of a majority of the other players through a vote.  It is enough for a majority of the other players to have said that the player can start a turn while not having indicated since that the player should not start a new turn.

**Comment by MrHug** [comment]
Again, I will not object to this ruling, making unanimity impossible. Will leave the closing to @jdonkervliet.

**Comment by jdonkervliet** [comment]
Ack.
