### ISSUE TITLE
I will be back!!!

### ISSUE THREAD

**Issue by arthurbik** [pimotte/nomic#50]
I don't really have the time to keep up with everything while writing my thesis. Would it be possible to join again when I have time? (I imagine that each vote being effectively a unanimous vote is not ideal)

**Comment by MrHug** [comment]
Hehe, I suppose writing a thesis is something we're all gonna have to do at some point. What is your expected finish time?

**Comment by arthurbik** [comment]
The end of the month, earlier if everything goes right.

**Comment by MrHug** [comment]
So let's quickly get #51 through to make this easier for you then?
