### ISSUE TITLE
Claiming my Trophy

### ISSUE THREAD

**Issue by pimotte** [pimotte/nomic#52]
Rule 327 grants the points upon proposition of the pull request. Hence, the proposing of 1900 rule changes including quotes would win me the game. The only thing preventing me from doing so is that Github will kick me out for spam. Hence, rule 329 allows me to describe my intended course of actions instead. Uniqueness is not required, just encouraged. Hence, the proposition of my rule changes will be to change the number of required points to win to 201-2101, respectively. Since the points are awarded on proposition, not on merging, this will lead to me getting 190 points, hence, winning the game.

 The accompanying PR text would say:
# 

Proposing random shit to win the game.

"It's over nine thousand!" - Vegeta (Dragon Ball Z, episode 28, "Goku's Arrival")
# I'm claiming 0.1 point for above quote.

Please vote on the validity of this method to win the game, @MrHug, @jdonkervliet, @arthurbik.

**Comment by jdonkervliet** [comment]
Well, submitting 1900 rule-changes is not infeasible, it just takes a certain amount of time. This amount of time is in fact larger than a few days. And when 1900 pull-requests are distributed over multiple days, you will not get kicked for spam.

**Comment by MrHug** [comment]
So... Are you saying @pimotte should just do this and then he does win the game? :P

**Comment by jdonkervliet** [comment]
Go for it, Pim.

**Comment by pimotte** [comment]
According to the [Oxford English Dictionary](https://www.oxforddictionaries.com/definition/english/infeasible). Infeasible means "Not possible to do easily or conveniently; impracticable". While I may not be blocked by Github, submitting 1900 pull requests is certainly not possible to do easily. Hence I move I do fulfill the conditions of 329.

**Comment by jdonkervliet** [comment]
Not saying I agree with you, but I just want to state that _if_ you get this throphy, we will reset the game state to the state before #48 was adopted.

**Comment by arthurbik** [comment]
If you would do this, then you would be awarded by 190. The rule does not say we are talking about points until later.

On to a more serious point. Please explain why rule 239 does not cause a conflict with rule 112. 

According to rule 239, the gamestate is reset whenever a player would win the game. Therefore rule 239 alters the state of affairs that constitutes winning from achieving n points to the impossible state of affairs.

**Comment by pimotte** [comment]
I would argue that 239 does not argue the state of affairs that constitutes winning. (In fact, in this construction, I am still winning by achieving 200 points, except that there's the shortcut from the second part of 239, which, again does not alter the point-achieving part.) 

239 defines what happens to the game after it has been won.

**Comment by arthurbik** [comment]
> Whenever a player would win the game, instead,...

Rule 329 clearly states instead, so I would say that rule 329 says that the game is not winnable.

**Comment by pimotte** [comment]
Mmmmm. I guess you have a point there. :P

**Comment by jdonkervliet** [comment]
Since @arthurbik found an inconsistency in the rules, does this mean he won?

**Comment by pimotte** [comment]
Nope, since it doesn't cause play to stop. This simply means that 329 is fully void, in accordance with "Constitution Trumps Law".

**Comment by MrHug** [comment]
So... Is this resolved then? @pimotte doesn't get a trophy and the rule can stay, although it is meaningless?

**Comment by arthurbik** [comment]
I think so, yes.

**Comment by pimotte** [comment]
I agree.
