### ISSUE TITLE
The people vs @pimotte 1

### ISSUE THREAD

**Issue by MrHug** [pimotte/nomic#59]
I hereby charge @pimotte with a violation of rule 333 in his merging of #55 and #57.

He has added 0.1 point to his score, without explicitly mentioning this in his PRs. Due to the similar nature of the offenses, I would like to have a joint Trial for both violations. Although the rules do not explicitly allow this, rule 116 ("Chaos is allowed") allows me to do so.

In accordance with rule 324 I hereby dub myself the prosecutor of this Trial.

**Comment by MrHug** [comment]
The prosecution calls forth @jdonkervliet for Jury duty. Once the defendant has acknowledged this Trial, I will present my opening statement and penalty demand.

**Comment by jdonkervliet** [comment]
Oh my god, all this power.

**Comment by pimotte** [comment]
I acknowledge this Trial, and for the purposes of following the guidelines, I call forth @jdonkervliet for Jury duty.

**Comment by MrHug** [comment]
Alright, with the jury established I shall proceed to the opening statement.

I will try to be brief in my opening statement, though as the Jury may be aware, brevity is not the prosecution's most developed quality.

### _Charges_

 The prosecution charges the defendant @pimotte with two breaches of rule 333. The rule states that in order to legally get the 0.1 point, the points need to be _explicitly_ claimed in the PR (Pull Request). The defendant made no notion of this in his PR. I will list my claim for each violation separately.

Violation 1 (V1). Breaking rule 333 in the merging of #55, the 0.1 points were not explicitly claimed in the pull request. I claim the defendant is Guilty of this crime.

Violation 2 (V2). Breaking rule 333 in the merging of #57, the 0.1 points were not explicitly claimed in the pull request. I claim the defendant is Guilty of this crime.

### _Penalty Demands_

My sentence demands are as follows. 
First we should restore the gamestate and remove the **0.2 illegal points** the defendant has claimed for himself.
Second I believe a penalty totaling **1 full point** is in order as I believe the defendant must have been aware of the transgressions he was committing. 

### Justification

As I believe little debate about the 0.2 illegal points should be required, please allow me to further describe while I feel the total penalty of 1 point is justified. 

First the prosecution will present evidence that makes it perfectly clear that the defendant was aware of his failings to uphold the rules.
Second the prosecution will present the reasoning as to why this should lead to an actual (as of yet unprecedented) point penalty.

Some weeks ago when the procedure of Trial was introduced the defendant was informed in person by the prosecution that he had a PR that could lead to a Trial against him if it were merged at that time. The defendant quickly discovered that he had forgotten to explicitly claim his points that rule 308 allowed him and [did so to rectify this oversight](https://github.com/pimotte/nomic/pull/28#issuecomment-222668580). This shows that the defendant is aware of the need to explicitly claim points, yet he has neglected to do so in the violations of rule 333 which uses very similar wording. Clearly the defendant has trouble learning from his mistakes and perhaps a penalty can help to ensure such oversights are prevented in the future.

Not only can it thus be proven that he is aware of the need to explicitly claim points when a rule tells you to do so, the defendant is also the last editor of rule 333, the rule he is charged with breaking. If a player can be so careless to break a rule within the same Pull Request in which he is proposing that rule (#55), I believe this behavior should be penalized most severely.

The prosecution argues therefore that these violations can not be considered as mere mistakes on the part of the defendant, thus nullifying the possibility of using such a claim as a defense for a favourable ruling like in previous Trials (The people vs @MrHug 1 #34, and The people vs @jdonkervliet 1 #44). Instead the prosecution claims that the defendant had ample warning and opportunity to rectify these oversights, as he was the one who proposed and also the one to merge the offending Pull Requests.

### Questions to the Defendant

With that I would very much like to hear the defendant's side of the story, including an answer to the the following questions:
- As the defendant is the last person to have changed rule 333, how is it possible that he did not adhere to the clear conditions outlined within it?
- If the defendant was previously aware of the requirements outlined in rule 308, why did he now commit the very offensive he managed to avoid only by grace of the prosecution last time?

**Comment by pimotte** [comment]
The answers to the prosecution's questions are far more boring than the entirety of their opening statement. It was merely simple oversight. In particular, an oversight of a construction that is, in my opinion, overly convoluted and disruptive to gameplay. However, this is a matter for future rule changes. 

Therefore, I will plead _Guilty_ on accounts of both violations. 

I fully agree with the restoration of the game state, resulting in a 0.2 point deduction. 

I will accept the punishment that the jury decides on, but in order to provide them with "all this power", I will suggest an alternative punishment of a 0 point deduction. I'm also just going to leave [this](https://en.wikipedia.org/wiki/Jury_nullification) here.

**Comment by MrHug** [comment]
I agree that if the defendant feels a rule is convoluted or disruptive this is not a matter for a Trial, but for future rule-changes. However this only makes my claim that the defendant could have prevented these mishaps quite easily a lot stronger, as the defendant could have pushed for this in his last adaption of what is currently rule 333.

Whereas the jury is indeed allowed to go for a Not Guilty verdict, despite both parties in the trial demanding a Guilty verdict, I urge the jury to consider the precedent that would set. If we do not punish violations of rules against which players have been warned in the past, where do we draw the line?

I have no more questions for the defendant, so as far as the prosecution is concerned the Jury (@jdonkervliet) may ask any questions it has before we move on to closing statements.

**Comment by jdonkervliet** [comment]
@MrHug it seems you were quite active on GitHub around the time #57 was merged. If you care so much about this rule, why did you not mention the omission of the explicit claims in a message on the pr?

**Comment by MrHug** [comment]
My reasoning is simple, I did not consider that Pull Request anywhere near ready to be merged. You will find that I was voting against the PR and as far as I was concerned a debate about this rule was still in progress. This is also made clear by this comment by the defendant: https://github.com/pimotte/nomic/pull/57#issuecomment-225620163. With your vote in favor of the matter, the PR was immediately closed and merged. Had there been more time for debate I could have mentioned it to the defendant. 

Then again, I would like to point out that I have no obligation in pointing out mistakes that lead to violations to other players. Whereas lying as a prosecutor is not explicitly forbidden by the Trial procedure, allow me to be honest with you. Going to Trial is something I enjoy doing and if people are about to commit violations that disrupt gameplay, but not sufficiently to ruin the game (aka, require effort, a Trial and a punishment, but not a complete reset of the game), then I am likely to remain silent and prosecute them after committing the violation.

In the case of #57 then, there was not even sufficient time to tell the defendant of his oversight as the debate was still ongoing in my opinion. In general though, I can not promise you that I would have told the defendant about the upcoming violation.

**Comment by MrHug** [comment]
In addition, let me address why I did not prosecute him for #55 earlier. The reason is that with the introduction of rule 326 "Let it Go!", the gamestate would have frozen at that point in time, making it even harder for #42 to be merged, something that the defendant had already indicated he wanted to get through asap. After that I have had little time to formulate my case properly (I wanted to write an opening statement before actually putting the defendant on Trial), thus we now have a double violation to deal with.

I can only offer my apologies that I let the defendant proceed with the second violation by not prosecuting him for the first one sooner, but unfortunately busy weekends leave me little time for this game sometimes.

**Comment by jdonkervliet** [comment]
Time for the closing statements then.

**Comment by MrHug** [comment]
Regarding this closing statement, I can really be brief.

The defendant has not denied the violations and the prosecution has outlined a clear case showing that the defendant was previously aware of the strict regulations within the rules.
If the defendant disagrees with these rules, then he should have included that change in #55. Instead he choose to violate the rule he proposed within that very same Pull Request. 

The purpose of Trials is to bring to light violations and make sure they do not happen again. Sometimes I believe a Trial can be enough in and of itself for that purpose, however in this case a warning has been shown to not be sufficient to remind the defendant of his obligations when claiming extra points. Perhaps then, a penalty will help him remember next time.

To speak with the words of prosecuting prodigy: "Need I remind you!? The foolish receive no mercy..."

**Comment by pimotte** [comment]
"Only the guy who isn't rowing has time to rock the boat." -Jean Paul Sartre

The defense rests.

**Comment by jdonkervliet** [comment]
Thank you both.

Well, it is obvious that in in life the only right course of action is that which nobody asks for. However, according to rule 324 the potential penalty I impose on Pim cannot exceed the flimsy penalty proposed by the prosecutor. That leaves we with only one proper course of action.

Pim, you are Not Guilty.

Furthermore, no serious damage has been done to the game state.

**Comment by pimotte** [comment]
I propose the defense that has been employed in this Trial will be known in the future as the "Trust-Jesse-to-YOLO-defense".

**Comment by MrHug** [comment]
I really do miss @arthurbik...

**Comment by jdonkervliet** [comment]
Thanks @pimotte.
