### ISSUE TITLE
Labels

### ISSUE THREAD

**Issue by MrHug** [pimotte/nomic#8]
Can we make GH labels like "amendment", "abolition", "new rule" etc to label PRs?

**Comment by pimotte** [comment]
I tried to add you as a collaborator to allow you to do this, but when I try to do so, it says "MrHug" is not a member of github.

**Comment by MrHug** [comment]
Wait wut? That's interesting...

EDIT: Hmm my change to the Readme is also not noted: https://github.com/pimotte/nomic/graphs/contributors

**Comment by pimotte** [comment]
The field I'm at (Settings->Collaborators) is not actually limited to people who have contributed. I get the same error for Jesse and Arthur.

**Comment by MrHug** [comment]
Oh... Well that's odd, let me try to add you to another repo of mine on GH.

EDIT: That worked just fine... Also something has worked, I am now collaborator ;)

**Comment by pimotte** [comment]
Yeah, you suddenly showed up, so I added you xD

**Comment by MrHug** [comment]
Good, closed then :)
